### ISSUE TITLE
DIY OpenSource display for EVs, TSDZ2 EBike motor and Xiaomi scooter

### ISSUE THREAD

**Issue by casainho** [OpenSourceEBike/Color_LCD#124]
@geeksville, you did a very professional development on the display firmware and I decided to build a DIY and OpenSource display based on the size and characteristics of SW102 and using your display firmware - this message is to let you know about it and give you a thank you.
I did read some very positive reviews of https://meshtastic.org/ -- congratulations!!

Pictures of the display using the same OLED 1.3 inches as SW102 display:
![image](https://user-images.githubusercontent.com/147128/141348654-cfceebab-44a6-4f76-9345-a822379e7a11.png)

![image](https://user-images.githubusercontent.com/147128/141348692-a118d14c-c104-44f7-896d-f33a62990310.png)

Video for 0.96 OLED screen:
https://www.youtube.com/watch?v=viimR74NPZk

Schematic:
![image](https://user-images.githubusercontent.com/147128/141348524-07a573b4-3b12-4d5b-96b3-2c903da2e11e.png)

Example of DIY board:
![image](https://user-images.githubusercontent.com/147128/141348846-daab362f-5479-4b44-8188-eeb629e9c431.png)

**Comment by geeksville** [comment]
Oh these l that's really cool.  Great work!  Someday I want to return to bike land and make an open source eshifter based on nrf52 and wireless.  And to make it nicely automatically integrate with ebikes.

**Comment by geeksville** [comment]
btw: your cool new board/project would probably almost 'just work' on one of the TTGO nrf52 based boards.  They have some nice, cheap, already shipping from china boards that have oled or eink screens (we use some of them on meshtastic)

**Comment by casainho** [comment]
> TTGO nrf52

Thanks but I am happy I didn´t went for that route, as currently they do not sell any board on their site with NRF52, seems they switched to ESP.

NRF52840 supports Bluetooth and ANT, and ANT is used to the EBike wireless standard communication (ANT+ LEV) so using ESP would be an disadvantage. We already built a fully wireless remote with NRF52 for EBikes and the coin battery works for about 2 years.

But in the end, I found we really need at least a very small display to give feedback if motor is turned on and the battery SOC - and I dreamed with the fully wireless remote with eink display, but the modules misses the back light, so, I am back to a wired display :-)

![image](https://user-images.githubusercontent.com/147128/141440947-f1145930-cf9b-4068-8761-3963de961795.png)

![image](https://user-images.githubusercontent.com/147128/141441006-c54cb62e-91ad-42bd-970a-195878b5b78e.png)


![image](https://user-images.githubusercontent.com/147128/141441127-19b8f4b7-6440-4b32-9d9e-d80247e48b76.png)

![image](https://user-images.githubusercontent.com/147128/141441166-3bd45a31-eb45-48c0-84f1-5f1e3e0c4f9e.png)

![image](https://user-images.githubusercontent.com/147128/141441204-d56b772d-4c03-4615-a819-d7c8ac69c0c3.png)
